# Generated by Django 4.2 on 2024-11-26 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_section_customuser_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarking',
            name='evaluator',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'evaluation_member'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_made', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentmarking',
            unique_together={('student', 'evaluation', 'criterion', 'evaluator')},
        ),
    ]
