# Generated by Django 5.0.1 on 2024-12-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentmarking_evaluator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfileupload',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
    ]
