# Generated by Django 5.0.1 on 2024-12-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentfileupload_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfileupload',
            name='group',
        ),
    ]
