# Generated by Django 5.2 on 2025-05-03 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_studentfileupload_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarking',
            name='evaluated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
